@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.enderthing.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;