@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.enderthing.items;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;