modLoader="javafml"
loaderVersion="[38,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/Enderthing/issues"

[[mods]]
modId="enderthing"
version="${file.jarVersion}"
displayName="Enderthing"
description='''
Shared inventories with chests and keys
'''
displayURL="https://github.com/gigaherz/Enderthing"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.enderthing]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.10,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enderthing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"