modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/Enderthing/issues"

[[mods]]
modId="enderthing"
version="${file.jarVersion}"
displayName="Enderthing"
description='''
Shared inventories with chests and keys
'''
displayURL="https://github.com/gigaherz/Enderthing"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.enderthing]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.75-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enderthing]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6,1.21)"
    ordering="NONE"
    side="BOTH"