@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.enderthing.storage;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;