@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.enderthing.integration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;