@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.enderthing.storage;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;