@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.enderthing.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;